/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSpace201Response,
  CreateSpaceRequest,
  GetSpaceRolesById200Response,
  MultiEntityResultSpacePermission,
  MultiEntityResultSpaceRole,
  MultiEntityResultSpaceRoleAssignment,
  PrincipalType,
  SetSpaceRoleAssignmentsRequestInner,
} from '../models';

export interface CreateSpaceOperationRequest {
    createSpaceRequest: CreateSpaceRequest;
}

export interface GetAvailableSpacePermissionsRequest {
    cursor?: string;
    limit?: number;
}

export interface GetAvailableSpaceRolesRequest {
    spaceId?: string;
    roleType?: string;
    principalId?: string;
    principalType?: PrincipalType;
    cursor?: string;
    limit?: number;
}

export interface GetSpaceRoleAssignmentsRequest {
    id: number;
    roleId?: string;
    roleType?: string;
    principalId?: string;
    principalType?: PrincipalType;
    cursor?: string;
    limit?: number;
}

export interface GetSpaceRolesByIdRequest {
    id: number;
}

export interface SetSpaceRoleAssignmentsRequest {
    id: number;
    setSpaceRoleAssignmentsRequestInner: Array<SetSpaceRoleAssignmentsRequestInner>;
}

/**
 * 
 */
export class EAPApi extends runtime.BaseAPI {

    /**
     * Creates a Space as specified in the payload.  Available as part of the [Role-Based Access Controls Beta](https://community.atlassian.com/forums/Confluence-articles/Beta-Simplify-space-access-in-Confluence-with-roles/ba-p/3044550).   **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to create spaces.
     * Create space
     */
    async createSpaceRaw(requestParameters: CreateSpaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSpace201Response>> {
        if (requestParameters.createSpaceRequest === null || requestParameters.createSpaceRequest === undefined) {
            throw new runtime.RequiredError('createSpaceRequest','Required parameter requestParameters.createSpaceRequest was null or undefined when calling createSpace.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuthDefinitions", ["write:space:confluence"]);
        }

        const response = await this.request({
            path: `/spaces`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.createSpaceRequest,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Creates a Space as specified in the payload.  Available as part of the [Role-Based Access Controls Beta](https://community.atlassian.com/forums/Confluence-articles/Beta-Simplify-space-access-in-Confluence-with-roles/ba-p/3044550).   **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to create spaces.
     * Create space
     */
    async createSpace(requestParameters: CreateSpaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSpace201Response> {
        const response = await this.createSpaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the available space permissions.  Available as part of the [Role-Based Access Controls Beta](https://community.atlassian.com/forums/Confluence-articles/Beta-Simplify-space-access-in-Confluence-with-roles/ba-p/3044550).   **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site.
     * Get available space permissions
     */
    async getAvailableSpacePermissionsRaw(requestParameters: GetAvailableSpacePermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MultiEntityResultSpacePermission>> {
        const queryParameters: any = {};

        if (requestParameters.cursor !== undefined) {
            queryParameters['cursor'] = requestParameters.cursor;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuthDefinitions", []);
        }

        const response = await this.request({
            path: `/space-permissions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves the available space permissions.  Available as part of the [Role-Based Access Controls Beta](https://community.atlassian.com/forums/Confluence-articles/Beta-Simplify-space-access-in-Confluence-with-roles/ba-p/3044550).   **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site.
     * Get available space permissions
     */
    async getAvailableSpacePermissions(requestParameters: GetAvailableSpacePermissionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MultiEntityResultSpacePermission> {
        const response = await this.getAvailableSpacePermissionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the available space roles.  Available as part of the [Role-Based Access Controls Beta](https://community.atlassian.com/forums/Confluence-articles/Beta-Simplify-space-access-in-Confluence-with-roles/ba-p/3044550).   **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site; if requesting a certain space\'s roles, permission to view the space.
     * Get available space roles
     */
    async getAvailableSpaceRolesRaw(requestParameters: GetAvailableSpaceRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MultiEntityResultSpaceRole>> {
        const queryParameters: any = {};

        if (requestParameters.spaceId !== undefined) {
            queryParameters['space-id'] = requestParameters.spaceId;
        }

        if (requestParameters.roleType !== undefined) {
            queryParameters['role-type'] = requestParameters.roleType;
        }

        if (requestParameters.principalId !== undefined) {
            queryParameters['principal-id'] = requestParameters.principalId;
        }

        if (requestParameters.principalType !== undefined) {
            queryParameters['principal-type'] = requestParameters.principalType;
        }

        if (requestParameters.cursor !== undefined) {
            queryParameters['cursor'] = requestParameters.cursor;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuthDefinitions", []);
        }

        const response = await this.request({
            path: `/space-roles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves the available space roles.  Available as part of the [Role-Based Access Controls Beta](https://community.atlassian.com/forums/Confluence-articles/Beta-Simplify-space-access-in-Confluence-with-roles/ba-p/3044550).   **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site; if requesting a certain space\'s roles, permission to view the space.
     * Get available space roles
     */
    async getAvailableSpaceRoles(requestParameters: GetAvailableSpaceRolesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MultiEntityResultSpaceRole> {
        const response = await this.getAvailableSpaceRolesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the space role assignments.  Available as part of the [Role-Based Access Controls Beta](https://community.atlassian.com/forums/Confluence-articles/Beta-Simplify-space-access-in-Confluence-with-roles/ba-p/3044550).   **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to view the space.
     * Get space role assignments
     */
    async getSpaceRoleAssignmentsRaw(requestParameters: GetSpaceRoleAssignmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MultiEntityResultSpaceRoleAssignment>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getSpaceRoleAssignments.');
        }

        const queryParameters: any = {};

        if (requestParameters.roleId !== undefined) {
            queryParameters['role-id'] = requestParameters.roleId;
        }

        if (requestParameters.roleType !== undefined) {
            queryParameters['role-type'] = requestParameters.roleType;
        }

        if (requestParameters.principalId !== undefined) {
            queryParameters['principal-id'] = requestParameters.principalId;
        }

        if (requestParameters.principalType !== undefined) {
            queryParameters['principal-type'] = requestParameters.principalType;
        }

        if (requestParameters.cursor !== undefined) {
            queryParameters['cursor'] = requestParameters.cursor;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuthDefinitions", []);
        }

        const response = await this.request({
            path: `/spaces/{id}/role-assignments`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves the space role assignments.  Available as part of the [Role-Based Access Controls Beta](https://community.atlassian.com/forums/Confluence-articles/Beta-Simplify-space-access-in-Confluence-with-roles/ba-p/3044550).   **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to view the space.
     * Get space role assignments
     */
    async getSpaceRoleAssignments(requestParameters: GetSpaceRoleAssignmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MultiEntityResultSpaceRoleAssignment> {
        const response = await this.getSpaceRoleAssignmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the space role by ID.  Available as part of the [Role-Based Access Controls Beta](https://community.atlassian.com/forums/Confluence-articles/Beta-Simplify-space-access-in-Confluence-with-roles/ba-p/3044550).   **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site.
     * Get space role by ID
     */
    async getSpaceRolesByIdRaw(requestParameters: GetSpaceRolesByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSpaceRolesById200Response>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getSpaceRolesById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuthDefinitions", []);
        }

        const response = await this.request({
            path: `/space-roles/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Retrieves the space role by ID.  Available as part of the [Role-Based Access Controls Beta](https://community.atlassian.com/forums/Confluence-articles/Beta-Simplify-space-access-in-Confluence-with-roles/ba-p/3044550).   **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site.
     * Get space role by ID
     */
    async getSpaceRolesById(requestParameters: GetSpaceRolesByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSpaceRolesById200Response> {
        const response = await this.getSpaceRolesByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sets space role assignments as specified in the payload.  Available as part of the [Role-Based Access Controls Beta](https://community.atlassian.com/forums/Confluence-articles/Beta-Simplify-space-access-in-Confluence-with-roles/ba-p/3044550).   **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to manage roles in the space.
     * Set space role assignments
     */
    async setSpaceRoleAssignmentsRaw(requestParameters: SetSpaceRoleAssignmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MultiEntityResultSpaceRoleAssignment>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling setSpaceRoleAssignments.');
        }

        if (requestParameters.setSpaceRoleAssignmentsRequestInner === null || requestParameters.setSpaceRoleAssignmentsRequestInner === undefined) {
            throw new runtime.RequiredError('setSpaceRoleAssignmentsRequestInner','Required parameter requestParameters.setSpaceRoleAssignmentsRequestInner was null or undefined when calling setSpaceRoleAssignments.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuthDefinitions", []);
        }

        const response = await this.request({
            path: `/spaces/{id}/role-assignments`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.setSpaceRoleAssignmentsRequestInner,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Sets space role assignments as specified in the payload.  Available as part of the [Role-Based Access Controls Beta](https://community.atlassian.com/forums/Confluence-articles/Beta-Simplify-space-access-in-Confluence-with-roles/ba-p/3044550).   **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to manage roles in the space.
     * Set space role assignments
     */
    async setSpaceRoleAssignments(requestParameters: SetSpaceRoleAssignmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MultiEntityResultSpaceRoleAssignment> {
        const response = await this.setSpaceRoleAssignmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
