/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSpace201Response,
  CreateSpaceRequest,
  GetSpaceById200Response,
  MultiEntityResultSpace,
  SpaceDescriptionBodyRepresentation,
  SpaceSortOrder,
} from '../models';

export interface CreateSpaceOperationRequest {
    createSpaceRequest: CreateSpaceRequest;
}

export interface GetSpaceByIdRequest {
    id: number;
    descriptionFormat?: SpaceDescriptionBodyRepresentation;
    includeIcon?: boolean;
    includeOperations?: boolean;
    includeProperties?: boolean;
    includePermissions?: boolean;
    includeRoleAssignments?: boolean;
    includeLabels?: boolean;
}

export interface GetSpacesRequest {
    ids?: Array<number>;
    keys?: Array<string>;
    type?: GetSpacesTypeEnum;
    status?: GetSpacesStatusEnum;
    labels?: Array<string>;
    favoritedBy?: string;
    notFavoritedBy?: string;
    sort?: SpaceSortOrder;
    descriptionFormat?: SpaceDescriptionBodyRepresentation;
    includeIcon?: boolean;
    cursor?: string;
    limit?: number;
}

/**
 * 
 */
export class SpaceApi extends runtime.BaseAPI {

    /**
     * Creates a Space as specified in the payload.  Available as part of the [Role-Based Access Controls Beta](https://community.atlassian.com/forums/Confluence-articles/Beta-Simplify-space-access-in-Confluence-with-roles/ba-p/3044550).   **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to create spaces.
     * Create space
     */
    async createSpaceRaw(requestParameters: CreateSpaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSpace201Response>> {
        if (requestParameters.createSpaceRequest === null || requestParameters.createSpaceRequest === undefined) {
            throw new runtime.RequiredError('createSpaceRequest','Required parameter requestParameters.createSpaceRequest was null or undefined when calling createSpace.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuthDefinitions", ["write:space:confluence"]);
        }

        const response = await this.request({
            path: `/spaces`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.createSpaceRequest,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Creates a Space as specified in the payload.  Available as part of the [Role-Based Access Controls Beta](https://community.atlassian.com/forums/Confluence-articles/Beta-Simplify-space-access-in-Confluence-with-roles/ba-p/3044550).   **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to create spaces.
     * Create space
     */
    async createSpace(requestParameters: CreateSpaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSpace201Response> {
        const response = await this.createSpaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a specific space.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to view the space.
     * Get space by id
     */
    async getSpaceByIdRaw(requestParameters: GetSpaceByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSpaceById200Response>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getSpaceById.');
        }

        const queryParameters: any = {};

        if (requestParameters.descriptionFormat !== undefined) {
            queryParameters['description-format'] = requestParameters.descriptionFormat;
        }

        if (requestParameters.includeIcon !== undefined) {
            queryParameters['include-icon'] = requestParameters.includeIcon;
        }

        if (requestParameters.includeOperations !== undefined) {
            queryParameters['include-operations'] = requestParameters.includeOperations;
        }

        if (requestParameters.includeProperties !== undefined) {
            queryParameters['include-properties'] = requestParameters.includeProperties;
        }

        if (requestParameters.includePermissions !== undefined) {
            queryParameters['include-permissions'] = requestParameters.includePermissions;
        }

        if (requestParameters.includeRoleAssignments !== undefined) {
            queryParameters['include-role-assignments'] = requestParameters.includeRoleAssignments;
        }

        if (requestParameters.includeLabels !== undefined) {
            queryParameters['include-labels'] = requestParameters.includeLabels;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuthDefinitions", ["read:space:confluence"]);
        }

        const response = await this.request({
            path: `/spaces/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns a specific space.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to view the space.
     * Get space by id
     */
    async getSpaceById(requestParameters: GetSpaceByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSpaceById200Response> {
        const response = await this.getSpaceByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all spaces. The results will be sorted by id ascending. The number of results is limited by the `limit` parameter and additional results (if available) will be available through the `next` URL present in the `Link` response header.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (\'Can use\' global permission). Only spaces that the user has permission to view will be returned.
     * Get spaces
     */
    async getSpacesRaw(requestParameters: GetSpacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MultiEntityResultSpace>> {
        const queryParameters: any = {};

        if (requestParameters.ids) {
            queryParameters['ids'] = requestParameters.ids;
        }

        if (requestParameters.keys) {
            queryParameters['keys'] = requestParameters.keys;
        }

        if (requestParameters.type !== undefined) {
            queryParameters['type'] = requestParameters.type;
        }

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        if (requestParameters.labels) {
            queryParameters['labels'] = requestParameters.labels;
        }

        if (requestParameters.favoritedBy !== undefined) {
            queryParameters['favorited-by'] = requestParameters.favoritedBy;
        }

        if (requestParameters.notFavoritedBy !== undefined) {
            queryParameters['not-favorited-by'] = requestParameters.notFavoritedBy;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        if (requestParameters.descriptionFormat !== undefined) {
            queryParameters['description-format'] = requestParameters.descriptionFormat;
        }

        if (requestParameters.includeIcon !== undefined) {
            queryParameters['include-icon'] = requestParameters.includeIcon;
        }

        if (requestParameters.cursor !== undefined) {
            queryParameters['cursor'] = requestParameters.cursor;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuthDefinitions", ["read:space:confluence"]);
        }

        const response = await this.request({
            path: `/spaces`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns all spaces. The results will be sorted by id ascending. The number of results is limited by the `limit` parameter and additional results (if available) will be available through the `next` URL present in the `Link` response header.  **[Permissions](https://confluence.atlassian.com/x/_AozKw) required**: Permission to access the Confluence site (\'Can use\' global permission). Only spaces that the user has permission to view will be returned.
     * Get spaces
     */
    async getSpaces(requestParameters: GetSpacesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MultiEntityResultSpace> {
        const response = await this.getSpacesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetSpacesTypeEnum = {
    Global: 'global',
    Collaboration: 'collaboration',
    KnowledgeBase: 'knowledge_base',
    Personal: 'personal',
    System: 'system',
    Onboarding: 'onboarding',
    XflowSampleSpace: 'xflow_sample_space'
} as const;
export type GetSpacesTypeEnum = typeof GetSpacesTypeEnum[keyof typeof GetSpacesTypeEnum];
/**
 * @export
 */
export const GetSpacesStatusEnum = {
    Current: 'current',
    Archived: 'archived'
} as const;
export type GetSpacesStatusEnum = typeof GetSpacesStatusEnum[keyof typeof GetSpacesStatusEnum];
